### ISSUE TITLE
javax is now moved to jakarta

### ISSUE THREAD

**Issue by alexanderankin** [sokomishalov/jackson-dataformat-soap#70]
this library fails with no class def error on modern apps due to javax being jakarta

**Comment by sokomishalov** [comment]
Hey @alexanderankin!
Thanks for raising this issue
I tend to split artifacts to support both jaxb and jakarta
WDYT?

**Comment by alexanderankin** [comment]
Awesome 👍 thank you, yeah that seems reasonable

**Comment by sokomishalov** [comment]
@alexanderankin you're welcome!
since I'm about to make such breaking changes - I'll follow the [recommendation of jackson maintainer](https://github.com/FasterXML/jackson-future-ideas/issues/32#issuecomment-857832846) and rename the project into `jackson-datatype-soap`

So from now on there is `jackson-datatype-soap-jaxb` for legacy jaxb annotations and `jackson-datatype-soap-jakarta` for jakarta annotations
